#!/bin/sh
# Sample debian/patches/00template script
# era Thu May 15 23:24:07 2003
# 2005 modified by Stefan Lippers-Hollmann <s.l-h@gmx.de>
# (C) 2007  Kel Modderman <kel@otaku42.de>

# This simply creates the equivalent of the hard-coded template.
# Adapt and hack to suit your needs.

file="$1"
shift

DPATCH_FILE="`echo ${file} | sed -e s/\.diff$// -e s/\.patch$//`.dpatch"

dpatch patch-template "`echo ${DPATCH_FILE##*/} | sed s/\.dpatch$//`" "$*" > "${DPATCH_FILE}"
cat ${file} >> "${DPATCH_FILE}"
